### PR TITLE
Update mod to 1.18.1

### PR DESCRIPTION
**Pull request by Geolykt**
A rather straightforward update

### CODE REVIEW

**Comment by eideehi** [comment]
Thanks for the pull request! Suddenly, would you be interested in managing this mod and its CurseForge project on my behalf? I don't intend to update EXP Bottling anymore, so it would be great if you could take over the administration.

**Comment by Geolykt** [comment]
Yeah, I could do that

**Comment by eideehi** [comment]
Excellent! So I'm going to transfer the project, can you send me a PM to my CurseForge account?

https://www.curseforge.com/members/eideehi/followers

**Comment by Geolykt** [comment]
Did it

**Pull request merged**
